# Generated by Django 5.2.7 on 2025-10-25 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('store_url', models.URLField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Mark this as the current season for the global leaderboard.')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='leaderboard.game')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='leaderboard.season')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Rules for this specific leaderboard.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='leaderboard.event')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, help_text='Points awarded for this leaderboard (e.g., 10 for 1st, 9 for 2nd...)')),
                ('notes', models.TextField(blank=True, help_text="Store raw result here (e.g., 'Time: 1:23.45', 'Score: 500,000')")),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='leaderboard.leaderboard')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='leaderboard.player')),
            ],
            options={
                'verbose_name_plural': 'Leaderboard Entries',
                'ordering': ['-points'],
                'unique_together': {('leaderboard', 'player')},
            },
        ),
    ]
