# Generated by Django 5.2.7 on 2025-10-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_details_public',
            field=models.BooleanField(default=False, help_text='If unchecked, only the event name and date will be public.'),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text="The ID from the YouTube URL (e.g., 'dQw4w9WgXcQ')", max_length=20),
        ),
    ]
